### ISSUE TITLE
transmission built with cmake requires libstdc++.so.6 (in contrast to version built with autotools)

### ISSUE THREAD

**Issue by pedro0311** [st-ty1/Artix_FreshTomato#2]
I'm writing here, because maybe you will have an idea what to do with this problem.
libstdc++.so.6 is quite big, and is not added by default when image is built with transmission (only for php/nginx and nano), thus this library can't be found on transmission-daemon start on some targets.

So, first autotools recipe:
```
transmission/stamp-h1:
	cd transmission && ./autogen.sh && \
		CFLAGS="-O3 -Wall -pipe -fno-delete-null-pointer-checks -funit-at-a-time -ffunction-sections -fdata-sections -fPIC --param large-function-growth=800 --param max-inline-insns-single=3600" \
		CPPFLAGS="-O3 -Wall -pipe -ffunction-sections -fdata-sections -fPIC --param large-function-growth=800 --param max-inline-insns-single=3600" \
		CXXFLAGS="-O3 -Wall -pipe -ffunction-sections -fdata-sections -fPIC --param large-function-growth=800 --param max-inline-insns-single=3600" \
		LDFLAGS="-L$(TOP)/zlib/staged/usr/lib -L$(TOP)/$(OPENSSLDIR)/staged/usr/lib -L$(TOP)/libcurl/lib/.libs -L$(TOP)/libevent/staged/usr/local/lib -Wl,--gc-sections -fPIC" \
		$(CONFIGURE) --prefix=/usr --enable-lightweight --enable-largefile --enable-utp \
			--disable-nls --disable-cli --without-gtk --disable-dependency-tracking \
			LIBCURL_CFLAGS="-I$(TOP)/libcurl/include" \
			LIBCURL_LIBS="-lcurl" \
			LIBEVENT_CFLAGS="-I$(TOP)/libevent/staged/usr/local/include" \
			LIBEVENT_LIBS="-levent" \
			OPENSSL_CFLAGS="-I$(TOP)/$(OPENSSLDIR)/staged/usr/include" \
			OPENSSL_LIBS="-lcrypto -lssl" \
			ZLIB_CFLAGS="-I$(TOP)/zlib/staged/usr/include" \
			ZLIB_LIBS="-lz"
	@touch $@
```

cmake recipe:
```
transmission/build/Makefile:
	@rm -rf transmission/build && mkdir -p transmission/build
	$(call patch_files,transmission)
	cd transmission/build && $(call CMAKE_CrossOptions, crosscompiled.cmake) && \
		cmake -DCMAKE_TOOLCHAIN_FILE=crosscompiled.cmake \
			-DCMAKE_INSTALL_PREFIX=/usr \
			-DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_RPATH=TRUE \
			-DCMAKE_C_FLAGS="-Wall $(EXTRACFLAGS) -ffunction-sections -fdata-sections -fPIC --param large-function-growth=800 --param max-inline-insns-single=3600" \
			-DCMAKE_CXX_FLAGS="-Wall $(EXTRACFLAGS) -ffunction-sections -fdata-sections -fPIC --param large-function-growth=800 --param max-inline-insns-single=3600 -fno-exceptions -fno-rtti" \
			-DCMAKE_EXE_LINKER_FLAGS="-Wl,--gc-sections -fPIC" \
			-DENABLE_LIGHTWEIGHT=TRUE -DENABLE_UTP=TRUE -DENABLE_NLS=FALSE -DENABLE_CLI=FALSE -DENABLE_GTK=FALSE -DENABLE_TESTS=FALSE \
			-DENABLE_NLS=FALSE -DINSTALL_DOC=FALSE -DUSE_SYSTEM_UTP=FALSE -DUSE_SYSTEM_DHT=FALSE -DUSE_SYSTEM_B64=FALSE -DWITH_SYSTEMD=FALSE \
			-DCURL_INCLUDE_DIR=$(TOP)/libcurl/include \
			-DCURL_LIBRARY=$(TOP)/libcurl/lib/.libs/libcurl.so \
			-DEVENT2_INCLUDE_DIR=$(TOP)/libevent/staged/usr/local/include \
			-DEVENT2_LIBRARY=$(TOP)/libevent/staged/usr/local/lib/libevent.so \
			-DOPENSSL_INCLUDE_DIR=$(TOP)/$(OPENSSLDIR)/staged/usr/include \
			-DOPENSSL_CRYPTO_LIBRARY=$(TOP)/$(OPENSSLDIR)/staged/usr/lib/libcrypto.so \
			-DOPENSSL_SSL_LIBRARY=$(TOP)/$(OPENSSLDIR)/staged/usr/lib/libssl.so \
			-DZLIB_INCLUDE_DIR=$(TOP)/zlib/staged/usr/include \
			-DZLIB_LIBRARY=$(TOP)/zlib/staged/usr/lib/libz.so \
			-DICONV_INCLUDE_DIR="" \
			-DICONV_LIBRARY="" \
			..
```

tr with autotools:
```
ldd /usr/bin/transmission-daemon
        libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x40169000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x4046d000)
        libz.so.1 => /usr/lib/libz.so.1 (0x40453000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x403f5000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x40212000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x401af000)
        libm.so.0 => /lib/libm.so.0 (0x4010e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x400da000)
        libc.so.0 => /lib/libc.so.0 (0x40489000)
        ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x400ff000)
        libdl.so.0 => /lib/libdl.so.0 (0x404f9000)
        **librt.so.0 => /lib/librt.so.0 (0x400ed000)**
```

tr with cmake:
```
ldd /usr/bin/transmission-daemon
        libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x40187000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x401cd000)
        libz.so.1 => /usr/lib/libz.so.1 (0x400a8000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x400e8000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x401e9000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x403cc000)
        libm.so.0 => /lib/libm.so.0 (0x40146000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x4015e000)
        libc.so.0 => /lib/libc.so.0 (0x404db000)
        ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x400d9000)
        libdl.so.0 => /lib/libdl.so.0 (0x4054b000)
        **libstdc++.so.6 => /lib/libstdc++.so.6 (0x4042f000)**
```

So we need some hack or patch, to eliminate this dependency in transmission caused by third-party/utp.
Otherwise, I'lll have to return to the version with autotools...

Adding `-fno-exceptions -fno-rtti` to CMAKE_CXX_FLAGS doesn't help...

BR
pedro

**Comment by st-ty1** [comment]
Maybe additional flag  -DENABLE_QT=OFF in transmission/build/Makefile target will work, as in the version 3.0 only folder transmission/qt has C++ source code . But in the end, this will be only a temporary solution: The change from C- to C++  - code in transmission source code has been announced by their developer.

**Comment by st-ty1** [comment]
Or insert -DENABLE_UTP=FALSE in transmission/build/Makefile target to turn off utp support
Or answer no.1 of [https://stackoverflow.com/questions/15058403/how-to-stop-cmake-from-linking-against-libstdc] might generate smaller tr code with utp included.
BR
st-ty1

**Comment by pedro0311** [comment]
> Maybe additional flag -DENABLE_QT=OFF in transmission/build/Makefile target will work

Nope, it doesn't help

> Or insert -DENABLE_UTP=FALSE in transmission/build/Makefile target to turn off utp support.

It's broken in 3.00 (causing build break)

The worst thing is this: https://github.com/transmission/transmission/commit/077f4d8d2b50adcd27720e8e8aa411bb819f6364

And this is the end of transmission on FT...

> CMake Error in /.../freshtomato-arm/release/src-rt-6.x.4708/router/transmission/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
>  Target "cmTC_c12ed" requires the language dialect "C11" (with compiler
>  extensions), but CMake does not know the compile flags to use to enable it.

Well, back to autotools... :(

**Comment by st-ty1** [comment]
Adding -fno-exceptions -fno-rtti to CMAKE_CXX_FLAGS and commenting/deactivating line 330 in CMakeLists.txt of main transmission directory: 
        set_property(TARGET UTP::UTP PROPERTY IMPORTED_LINK_INTERFACE_LANGUAGES "CXX")
 will wipe out libstdc++.so of the needed libs of tr-daemon.

**Comment by pedro0311** [comment]
OK, thanks, I'll give cmake a try (again) then.

**Comment by pedro0311** [comment]
Great it can be closed.
BTW: do you have some idea what we can do with above commit https://github.com/transmission/transmission/commit/077f4d8d2b50adcd27720e8e8aa411bb819f6364 ?

**Comment by st-ty1** [comment]
Would this be an issue anyway? Recommended C++ version is already  C++17
and toolchain is far away from that level; so what about the error message
if applying this commit?
BR st-ty1

pedro ***@***.***> schrieb am Sa., 8. Jan. 2022, 21:49:

**Comment by pedro0311** [comment]
In other words: are you able to build transmission in FT after this commit? Or at latest https://github.com/transmission/transmission/commit/d2e840c64cfd99f72e0b2d15bd8e9edadbf939a9 ?
